### PR TITLE
Enable builds for Windows

### PR DESCRIPTION
**Pull request by Jan-E**
It took some changes to make this extension Windows-aware...

### CODE REVIEW

**Comment by Jan-E** [comment]
The commenting out of AST_CHILD(CONST, 1) is not VC11 specific, however the build failed with a non-existing ZEND_AST_const or something like that.

**Comment by Jan-E** [comment]
@sgolemon Did you have a chance to look at this PR?

**Comment by sgolemon** [comment]
Sorry, didn't even notice this PR till now. (Poke me on twitter/@ SaraMG in the future if I'm unresponsive).

Seems reasonable, but I just modified ast-name.h so it won't apply, could you rebase? I'll happily merge it.

**Comment by Jan-E** [comment]
There is a new PR: https://github.com/sgolemon/astkit/pull/2

**Pull request closed without merging**
